name: frontend
health:
  path: /health
  timeout: 2
host: pokedextracker.com
image:
  repo: pokedextracker/pokedextracker.com
port: 4939
public: true
resources:
  requests:
    memory: 4Mi
    cpu: 20m
  limits:
    memory: 20Mi
    cpu: 50m
