name: frontend
health:
  path: /health
  timeout: 2
host: staging.pokedextracker.com
image:
  repo: pokedextracker/pokedextracker.com
port: 4939
public: true
resources:
  requests:
    memory: 4Mi
    cpu: 20m
  limits:
    memory: 20Mi
    cpu: 50m
extra_configs:
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/permanent-redirect: https://staging.pokedextracker.com
    name: www
    metadata:
      label:
        app: frontend
  spec:
    tls:
    - hosts:
      - www.staging.pokedextracker.com
    rules:
    - host: www.staging.pokedextracker.com
