name: frontend
processes:
  web:
    health:
      path: /health
      grace: 3
      interval: 3
      timeout: 2
    ingress:
      host: staging.pokedextracker.com
      path: /
    image:
      repo: pokedextracker/pokedextracker.com
    ports:
    - port: 4939
      public: true
      health: true
    resources:
      requests:
        memory: 4Mi
        cpu: 20m
      limits:
        memory: 20Mi
        cpu: 50m
extra_configs:
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/permanent-redirect: https://staging.pokedextracker.com
    name: www
    labels:
      app: frontend
      process: web
  spec:
    tls:
    - hosts:
      - www.staging.pokedextracker.com
    rules:
    - host: www.staging.pokedextracker.com
