language: node_js
sudo: false
env: 'CXX=g++-4.8'
node_js:
  - '5'
  - '6'
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
script:
  - npm run lint
